// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaCare.API.Data;

#nullable disable

namespace NovaCare.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415080827_FixNullability")]
    partial class FixNullability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovaCare.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NovaCare.API.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("MedicineId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("NovaCare.API.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "KN 4 Ave, Nyarugenge, Kigali",
                            IsActive = true,
                            Name = "Nyarugenge Main Branch",
                            Phone = "+250 788 123 456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "KK 15 Rd, Kicukiro, Kigali",
                            IsActive = true,
                            Name = "Kicukiro Medical Center",
                            Phone = "+250 722 987 654"
                        },
                        new
                        {
                            Id = 3,
                            Address = "KG 11 Ave, Remera, Kigali",
                            IsActive = true,
                            Name = "Remera Plaza Branch",
                            Phone = "+250 733 456 789"
                        },
                        new
                        {
                            Id = 4,
                            Address = "National University Ave, Huye",
                            IsActive = false,
                            Name = "Huye Branch",
                            Phone = "+250 788 654 321"
                        });
                });

            modelBuilder.Entity("NovaCare.API.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("NovaCare.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "KG 5 Ave, Kigali",
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mugisha.jean@gmail.com",
                            Name = "Mugisha Jean",
                            Phone = "+250 788 100 001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "KN 12 Rd, Kigali",
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "uwimana.alice@gmail.com",
                            Name = "Uwimana Alice",
                            Phone = "+250 722 100 002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "KK 8 Ave, Kigali",
                            CreatedAt = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "habimana.eric@yahoo.com",
                            Name = "Habimana Eric",
                            Phone = "+250 733 100 003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Huye Town",
                            CreatedAt = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mukamana.grace@gmail.com",
                            Name = "Mukamana Grace",
                            Phone = "+250 788 100 004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Remera, Kigali",
                            CreatedAt = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "niyonzima.p@gmail.com",
                            Name = "Niyonzima Patrick",
                            Phone = "+250 722 100 005"
                        });
                });

            modelBuilder.Entity("NovaCare.API.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("bit");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Amoxil",
                            Category = "Antibiotics",
                            Description = "A penicillin-type antibiotic used to treat a wide variety of bacterial infections.",
                            Form = "Capsule",
                            GenericName = "Amoxicillin",
                            ImagePath = "/medicines/amoxil.jpeg",
                            Price = 16900m,
                            RequiresPrescription = true,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Advil",
                            Category = "Pain Relief",
                            Description = "A nonsteroidal anti-inflammatory drug used to reduce fever and treat pain or inflammation.",
                            Form = "Tablet",
                            GenericName = "Ibuprofen",
                            ImagePath = "/medicines/advil.jpeg",
                            Price = 11000m,
                            RequiresPrescription = false,
                            Strength = "200mg"
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "Glucophage",
                            Category = "Diabetes",
                            Description = "An oral diabetes medicine that helps control blood sugar levels.",
                            Form = "Tablet",
                            GenericName = "Metformin",
                            ImagePath = "/medicines/glucophage.jpeg",
                            Price = 19500m,
                            RequiresPrescription = true,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Norvasc",
                            Category = "Cardiovascular",
                            Description = "A calcium channel blocker used to treat high blood pressure and coronary artery disease.",
                            Form = "Tablet",
                            GenericName = "Amlodipine",
                            ImagePath = "/medicines/norvasc.jpeg",
                            Price = 24100m,
                            RequiresPrescription = true,
                            Strength = "5mg"
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "Tylenol",
                            Category = "Pain Relief",
                            Description = "An analgesic and antipyretic used to treat mild to moderate pain and reduce fever.",
                            Form = "Tablet",
                            GenericName = "Paracetamol",
                            ImagePath = "/medicines/tylenol.jpeg",
                            Price = 7800m,
                            RequiresPrescription = false,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 6,
                            BrandName = "Prilosec",
                            Category = "Gastrointestinal",
                            Description = "A proton pump inhibitor used to treat gastroesophageal reflux disease and stomach ulcers.",
                            Form = "Capsule",
                            GenericName = "Omeprazole",
                            ImagePath = "/medicines/Prilosec.jpeg",
                            Price = 20800m,
                            RequiresPrescription = false,
                            Strength = "20mg"
                        },
                        new
                        {
                            Id = 7,
                            BrandName = "Zyrtec",
                            Category = "Respiratory",
                            Description = "An antihistamine used to relieve allergy symptoms such as runny nose and sneezing.",
                            Form = "Tablet",
                            GenericName = "Cetirizine",
                            ImagePath = "/medicines/Zyrtec.jpeg",
                            Price = 13000m,
                            RequiresPrescription = false,
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = 8,
                            BrandName = "Lipitor",
                            Category = "Cardiovascular",
                            Description = "A statin medication used to prevent cardiovascular disease and treat abnormal lipid levels.",
                            Form = "Tablet",
                            GenericName = "Atorvastatin",
                            ImagePath = "/medicines/Lipitor.jpeg",
                            Price = 29900m,
                            RequiresPrescription = true,
                            Strength = "20mg"
                        },
                        new
                        {
                            Id = 9,
                            BrandName = "Zithromax",
                            Category = "Antibiotics",
                            Description = "A macrolide antibiotic used to treat various bacterial infections.",
                            Form = "Tablet",
                            GenericName = "Azithromycin",
                            ImagePath = "/medicines/zithromax.jpeg",
                            Price = 26000m,
                            RequiresPrescription = true,
                            Strength = "250mg"
                        },
                        new
                        {
                            Id = 10,
                            BrandName = "Ventolin",
                            Category = "Respiratory",
                            Description = "A bronchodilator used to relieve bronchospasm in conditions such as asthma.",
                            Form = "Injection",
                            GenericName = "Salbutamol",
                            ImagePath = "/medicines/Ventolin.jpeg",
                            Price = 32500m,
                            RequiresPrescription = true,
                            Strength = "100mcg"
                        },
                        new
                        {
                            Id = 11,
                            BrandName = "Celin",
                            Category = "Vitamins",
                            Description = "An essential vitamin supplement to support immune function and overall health.",
                            Form = "Tablet",
                            GenericName = "Vitamin C",
                            ImagePath = "/medicines/Celin.jpeg",
                            Price = 8400m,
                            RequiresPrescription = false,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 12,
                            BrandName = "Cortef",
                            Category = "Dermatology",
                            Description = "A topical corticosteroid used to reduce inflammation, redness, and itching of the skin.",
                            Form = "Cream",
                            GenericName = "Hydrocortisone",
                            ImagePath = "/medicines/cortef.jpeg",
                            Price = 15600m,
                            RequiresPrescription = false,
                            Strength = "1%"
                        },
                        new
                        {
                            Id = 13,
                            BrandName = "Cozaar",
                            Category = "Cardiovascular",
                            Description = "An angiotensin receptor blocker used to treat high blood pressure.",
                            Form = "Tablet",
                            GenericName = "Losartan",
                            ImagePath = "/medicines/Cozaar.jpeg",
                            Price = 21500m,
                            RequiresPrescription = true,
                            Strength = "50mg"
                        },
                        new
                        {
                            Id = 14,
                            BrandName = "Flagyl",
                            Category = "Antibiotics",
                            Description = "An antibiotic and antiprotozoal medication used to treat bacterial and parasitic infections.",
                            Form = "Tablet",
                            GenericName = "Metronidazole",
                            ImagePath = "/medicines/Flagyl.jpeg",
                            Price = 14300m,
                            RequiresPrescription = true,
                            Strength = "400mg"
                        },
                        new
                        {
                            Id = 15,
                            BrandName = "Cipro",
                            Category = "Antibiotics",
                            Description = "A fluoroquinolone antibiotic used to treat a variety of bacterial infections.",
                            Form = "Tablet",
                            GenericName = "Ciprofloxacin",
                            ImagePath = "/medicines/Cipro.jpeg",
                            Price = 18200m,
                            RequiresPrescription = true,
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = 16,
                            BrandName = "Centrum",
                            Category = "Vitamins",
                            Description = "A comprehensive multivitamin supplement for daily nutritional support.",
                            Form = "Tablet",
                            GenericName = "Multivitamin",
                            ImagePath = "/medicines/Centrum.jpeg",
                            Price = 16200m,
                            RequiresPrescription = false,
                            Strength = "Complex"
                        },
                        new
                        {
                            Id = 17,
                            BrandName = "Voltaren",
                            Category = "Pain Relief",
                            Description = "A nonsteroidal anti-inflammatory drug used to treat pain and inflammatory disorders.",
                            Form = "Tablet",
                            GenericName = "Diclofenac",
                            ImagePath = "/medicines/Voltaren.jpeg",
                            Price = 12300m,
                            RequiresPrescription = false,
                            Strength = "50mg"
                        },
                        new
                        {
                            Id = 18,
                            BrandName = "Zantac",
                            Category = "Gastrointestinal",
                            Description = "An H2 blocker used to reduce stomach acid production and treat heartburn.",
                            Form = "Tablet",
                            GenericName = "Ranitidine",
                            ImagePath = "/medicines/Zantac.jpeg",
                            Price = 14900m,
                            RequiresPrescription = false,
                            Strength = "150mg"
                        },
                        new
                        {
                            Id = 19,
                            BrandName = "Canesten",
                            Category = "Dermatology",
                            Description = "An antifungal medication used to treat skin infections such as athletes foot and ringworm.",
                            Form = "Cream",
                            GenericName = "Clotrimazole",
                            ImagePath = "/medicines/Canesten.jpeg",
                            Price = 11700m,
                            RequiresPrescription = false,
                            Strength = "1%"
                        },
                        new
                        {
                            Id = 20,
                            BrandName = "Lantus",
                            Category = "Diabetes",
                            Description = "A long-acting insulin used to treat diabetes mellitus.",
                            Form = "Injection",
                            GenericName = "Insulin Glargine",
                            ImagePath = "/medicines/Lantus.jpeg",
                            Price = 59800m,
                            RequiresPrescription = true,
                            Strength = "100IU/ml"
                        },
                        new
                        {
                            Id = 21,
                            BrandName = "Zestril",
                            Category = "Cardiovascular",
                            Description = "An ACE inhibitor used to treat high blood pressure and heart failure.",
                            Form = "Tablet",
                            GenericName = "Lisinopril",
                            ImagePath = "/medicines/Zestril.jpeg",
                            Price = 19500m,
                            RequiresPrescription = true,
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = 22,
                            BrandName = "Vibramycin",
                            Category = "Antibiotics",
                            Description = "A tetracycline antibiotic used to treat bacterial infections and prevent malaria.",
                            Form = "Capsule",
                            GenericName = "Doxycycline",
                            ImagePath = "/medicines/Vibramycin.jpeg",
                            Price = 15600m,
                            RequiresPrescription = true,
                            Strength = "100mg"
                        },
                        new
                        {
                            Id = 23,
                            BrandName = "Claritin",
                            Category = "Respiratory",
                            Description = "A non-drowsy antihistamine used to relieve symptoms of seasonal allergies.",
                            Form = "Tablet",
                            GenericName = "Loratadine",
                            ImagePath = "/medicines/Claritin.jpeg",
                            Price = 13600m,
                            RequiresPrescription = false,
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = 24,
                            BrandName = "Caltrate",
                            Category = "Vitamins",
                            Description = "A calcium supplement with vitamin D for bone health support.",
                            Form = "Tablet",
                            GenericName = "Calcium + Vitamin D",
                            ImagePath = "/medicines/Caltrate.jpeg",
                            Price = 18200m,
                            RequiresPrescription = false,
                            Strength = "600mg"
                        });
                });

            modelBuilder.Entity("NovaCare.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerId_External")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPrescription")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NovaCare.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PrescriptionFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrescriptionImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("NovaCare.API.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("NovaCare.API.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("NovaCare.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@novacare.rw",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$jMB7.6xlZUYdWazmTtIToO8sp1Fv8ls6xPo7G/yTtuCBP/zq8yNdm",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 2, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "rachel@novacare.rw",
                            FirstName = "Rachel",
                            IsActive = true,
                            LastName = "Green",
                            PasswordHash = "$2a$11$Aud1nPFualk4FDnVU5KT/ulvxgUxtSa2mjrlfrasZVKIIB3aZwSPe",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 2,
                            CreatedAt = new DateTime(2025, 3, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marcus@novacare.rw",
                            FirstName = "Marcus",
                            IsActive = true,
                            LastName = "Lee",
                            PasswordHash = "$2a$11$Aud1nPFualk4FDnVU5KT/ulvxgUxtSa2mjrlfrasZVKIIB3aZwSPe",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 3,
                            CreatedAt = new DateTime(2025, 3, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatima@novacare.rw",
                            FirstName = "Fatima",
                            IsActive = true,
                            LastName = "Al-Rashid",
                            PasswordHash = "$2a$11$Aud1nPFualk4FDnVU5KT/ulvxgUxtSa2mjrlfrasZVKIIB3aZwSPe",
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            CreatedAt = new DateTime(2025, 4, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james@novacare.rw",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Carter",
                            PasswordHash = "$2a$11$S7dudiRq230EYCsYZ1Jewe/EZJkb4NEJBMZGui1mJa/EN/KYSfEq.",
                            Role = 3
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            CreatedAt = new DateTime(2025, 5, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sophie@novacare.rw",
                            FirstName = "Sophie",
                            IsActive = true,
                            LastName = "Nguyen",
                            PasswordHash = "$2a$11$S7dudiRq230EYCsYZ1Jewe/EZJkb4NEJBMZGui1mJa/EN/KYSfEq.",
                            Role = 3
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 3,
                            CreatedAt = new DateTime(2025, 6, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar@novacare.rw",
                            FirstName = "Omar",
                            IsActive = true,
                            LastName = "Hassan",
                            PasswordHash = "$2a$11$S7dudiRq230EYCsYZ1Jewe/EZJkb4NEJBMZGui1mJa/EN/KYSfEq.",
                            Role = 3
                        });
                });

            modelBuilder.Entity("NovaCare.API.Models.AuditLog", b =>
                {
                    b.HasOne("NovaCare.API.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovaCare.API.Models.Batch", b =>
                {
                    b.HasOne("NovaCare.API.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NovaCare.API.Models.Medicine", "Medicine")
                        .WithMany("Batches")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("NovaCare.API.Models.ContactMessage", b =>
                {
                    b.HasOne("NovaCare.API.Models.Branch", "Branch")
                        .WithMany("ContactMessages")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("NovaCare.API.Models.Order", b =>
                {
                    b.HasOne("NovaCare.API.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NovaCare.API.Models.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NovaCare.API.Models.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("NovaCare.API.Models.OrderItem", b =>
                {
                    b.HasOne("NovaCare.API.Models.Medicine", "Medicine")
                        .WithMany("OrderItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaCare.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NovaCare.API.Models.Sale", b =>
                {
                    b.HasOne("NovaCare.API.Models.Branch", "Branch")
                        .WithMany("Sales")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NovaCare.API.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NovaCare.API.Models.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovaCare.API.Models.SaleItem", b =>
                {
                    b.HasOne("NovaCare.API.Models.Medicine", "Medicine")
                        .WithMany("SaleItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaCare.API.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("NovaCare.API.Models.User", b =>
                {
                    b.HasOne("NovaCare.API.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("NovaCare.API.Models.Branch", b =>
                {
                    b.Navigation("ContactMessages");

                    b.Navigation("Orders");

                    b.Navigation("Sales");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NovaCare.API.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("NovaCare.API.Models.Medicine", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("OrderItems");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("NovaCare.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NovaCare.API.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NovaCare.API.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
